/** Work-owned terminal strings. Workbench composes them into its existing locale runtime. */
export const WORK_EN: Record<string, string> = {
  "推进这个 Goal": "Advance this Goal",
  "复制命令": "Copy command",
  "命令已复制到剪贴板": "Command copied to the clipboard",
  "填入不发送": "Fill without sending",
  "重新打开": "Reopen",
  "添加终端": "Add terminal",
  "关闭终端": "Close terminal",
  "收起终端": "Collapse terminal",
  "展开终端": "Expand terminal",
  "未安装": "Not installed",
  "需要先安装 CLI": "Install the CLI first",
  "以下 CLI 未安装：{list}。安装后刷新页面即可使用。": "These CLIs are not installed: {list}. Install them, then refresh the page to use them.",
  "自定义命令": "Custom command",
  "终端已退出": "Terminal exited",
  "终端已退出（退出码 {code}）": "Terminal exited (exit code {code})",
  "终端进程已退出": "Terminal process exited",
  "退出码": "Exit code",
  "进程在启动后立即退出，常见原因：命令未安装、不在 PATH 中或工作目录不存在。": "The process exited immediately after starting. Common causes: the command is not installed, missing from PATH, or the working directory does not exist.",
  "没有终端。点右上角「添加终端」在这个 Goal 上打开 TUI。": "No terminal yet. Use Add terminal in the top-right to open a TUI on this Goal.",
  "还没有终端": "No terminal yet",
  "点右上角「添加终端」，在这个 Goal 上打开常用 Runtime 或自定义命令。": "Use Add terminal in the top-right to open a common Runtime or a custom command on this Goal.",
  "请选择要打开的 TUI": "Choose a TUI to open",
  "在这个 Goal 上打开终端": "Open a terminal on this Goal",
  "标签只属于当前 Goal。打开不会自动发送或领取。": "This tab belongs only to the current Goal. Opening it does not send a prompt or claim the work.",
  "参数": "Arguments",
  "工作目录": "Working directory",
  "继续会话 ID": "Resume session ID",
  "继续会话 ID（可选）": "Resume session ID (optional)",
  "终端面板": "Terminal pane",
  "调整终端宽度": "Resize terminal",
  "调整终端宽度，双击收起": "Resize the terminal. Double-click to collapse",
  "打开项目后，Goal 右侧可以添加终端": "After opening a project, add a terminal to the right of the Goal",
  "打开项目后，Goal 详情右侧会出现终端栏。点「添加终端」即可在当前 Goal 上打开 TUI。": "After you open a project, a terminal pane appears on the right of the Goal. Use Add terminal to open a TUI on the current Goal.",
  "打开失败": "Could not open",
  "桌面终端通道不可用，请从 GoalBoard App 打开。": "The desktop terminal channel is unavailable. Open this page from the GoalBoard App.",
  "正在启动终端…": "Starting terminal…",
  "正在连接终端…": "Connecting to the terminal…",
  "正在重新连接终端…": "Reconnecting to the terminal…",
  "终端已连接": "Terminal connected",
  "已回到正在运行的终端": "Reconnected to the running terminal",
  "终端进程已不在，可重新打开": "The terminal process is gone. You can reopen it.",
  "打开终端需要先把这个项目关联到一个工作目录": "Associate this project with a working directory before opening a terminal",
  "终端": "Terminal",
  "终端通道连接失败": "Could not connect to the terminal",
  "终端通道已断开": "The terminal connection dropped",
  "本地终端通道校验失败": "Local terminal channel check failed",
};
