import assert from "node:assert/strict";
import test from "node:test";
import { DEMO_BOARD_ID } from "@adeptify/goalboard-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("momentum loads on demand, retries failure, selects topology and queue, filters, zooms and opens the same Goal without writes", { timeout: 60_000 }, async (t) => {
  const browser = await openGoalBrowser(t);
  if (!browser) return;
  const { store, origin, before, sessionId, command, evaluate, waitFor, click, reloadPage } = browser;
  await command("Network.enable", {}, sessionId);
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1100, deviceScaleFactor: 1, mobile: false }, sessionId);
  await command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] }, sessionId);
  await command("Page.navigate", { url: origin + "/goals/V1" }, sessionId);
  await command("Page.bringToFront", {}, sessionId);
  const dom = (selector: string) => "document.querySelector(" + JSON.stringify(selector) + ")";
  await waitFor("document.readyState === 'complete' && " + dom("[data-goal-momentum]"));
  assert.equal(await evaluate(dom("[data-goal-momentum]") + ".dataset.loaded"), "false");
  await command("Network.setBlockedURLs", { urls: [origin + "/api/board/momentum*"] }, sessionId);
  await click('[data-navigator-view="graph"]');
  await waitFor(dom("[data-retry-goal-momentum]") + ".hidden === false && !" + dom("[data-goal-momentum]") + ".hasAttribute('aria-busy')");
  assert.equal(await evaluate(dom("[data-momentum-node]")), null);
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).runs, before.runs);
  await command("Network.setBlockedURLs", { urls: [] }, sessionId);
  await click("[data-retry-goal-momentum]");
  await waitFor(dom("[data-goal-momentum]") + ".dataset.loaded === 'true' && " + dom('[data-momentum-node][data-goal-id="INTERFACES"]'));
  const visibleGoals = before.goals.filter(goal => !goal.archived_at && !goal.trashed_at);
  assert.equal(await evaluate("document.querySelectorAll('[data-momentum-node]').length"), visibleGoals.length);
  const edge = '[data-graph-edge][data-edge-from="CORE"][data-edge-to="INTERFACES"]';
  await waitFor(dom(edge + " path") + ".getAttribute('d')?.startsWith('M ')");
  await click('[data-momentum-node][data-goal-id="INTERFACES"]');
  assert.equal(await evaluate(dom('[data-momentum-detail="INTERFACES"]') + ".hidden"), false);
  assert.equal(await evaluate(dom(edge) + ".classList.contains('is-selected-path')"), true);
  await click('.momentum-queue-item[data-momentum-select="DESKTOP"]');
  assert.equal(await evaluate(dom('[data-momentum-node][data-goal-id="DESKTOP"]') + ".getAttribute('aria-pressed')"), "true");
  assert.equal(await evaluate(dom('[data-momentum-detail="INTERFACES"]') + ".hidden"), true);
  await click('[data-momentum-period="30"]');
  assert.equal(await evaluate(dom('[data-momentum-period-panel="30"]') + ".hidden"), false);
  assert.equal(await evaluate(dom('[data-momentum-period-panel="7"]') + ".hidden"), true);
  await click('[data-momentum-filter="open"]');
  assert.equal(await evaluate(dom('[data-momentum-node][data-goal-id="CORE"]') + ".hidden"), true);
  assert.equal(await evaluate(dom(edge) + ".hasAttribute('hidden')"), true);
  await click('[data-momentum-filter="all"]');
  assert.equal(await evaluate(dom('[data-momentum-node][data-goal-id="CORE"]') + ".hidden"), false);
  const initialZoom = await evaluate<number>("Number(" + dom("[data-graph-stage]") + ".dataset.graphScale)");
  await click('[data-graph-zoom="in"]');
  assert.ok(await evaluate<number>("Number(" + dom("[data-graph-stage]") + ".dataset.graphScale)") > initialZoom);
  const manualZoom = await evaluate<number>("Number(" + dom("[data-graph-stage]") + ".dataset.graphScale)");
  await reloadPage();
  await waitFor(dom("[data-goal-momentum]") + ".dataset.loaded === 'true'");
  assert.equal(await evaluate<number>("Number(" + dom("[data-graph-stage]") + ".dataset.graphScale)"), manualZoom);
  assert.equal(await evaluate(dom('[data-momentum-period-panel="30"]') + ".hidden"), false);
  assert.equal(await evaluate(dom('[data-momentum-detail="DESKTOP"]') + ".hidden"), false);
  await click('[data-graph-zoom="fit"]');
  assert.equal(await evaluate(dom("[data-graph-viewport]") + ".scrollLeft"), 0);
  await reloadPage();
  await waitFor(dom("[data-goal-momentum]") + ".dataset.loaded === 'true'");
  assert.equal(await evaluate(dom('[data-momentum-period-panel="30"]') + ".hidden"), false);
  assert.equal(await evaluate(dom('[data-momentum-detail="DESKTOP"]') + ".hidden"), false);
  await click('[data-momentum-detail="DESKTOP"] a[href$="/goals/DESKTOP"]');
  await waitFor(dom('[data-goal-event-document][data-goal-view="DESKTOP"]'));
  assert.equal(await evaluate("location.pathname"), "/goals/DESKTOP");
  const after = store.snapshot(DEMO_BOARD_ID);
  assert.deepEqual(after.goals, before.goals);
  assert.deepEqual(after.relations, before.relations);
  assert.deepEqual(after.runs, before.runs);
});
