import type { McpToolDefinition } from "./protocol.js";
import {
  V1_COMMON,
  V1_CLAIM_ROLE,
  V1_STRING,
  V1_STRING_ARRAY,
  V1_LEASE_SECONDS,
  V1_RENEW_LEASE_SECONDS,
  DRAFT_DIALOGUE_FACT,
  DRAFT_DIALOGUE_ASSUMPTION,
  CONTRACT_PROPOSAL_GOAL_PAYLOAD,
  GOAL_TREE_POLICY_FIELDS,
  GOAL_TREE_PROPOSAL_NARRATIVE,
  GOAL_TREE_ITEM,
  GOAL_TREE_ITEM_DECISION,
  PLANNING_METHOD_PACK,
  v1PayloadTool,
} from "./tool-schemas.js";

export const V1_TOOLS: McpToolDefinition[] = [
  {
    name: "goalboard_v1_initialize",
    description: "初始化 SQLite GoalBoard 真相源。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        title: { type: "string" },
        actor_id: { type: "string" },
        idempotency_key: { type: "string" },
      },
      required: ["board_id", "title", "actor_id", "idempotency_key"],
    },
  },
  {
    name: "goalboard_v1_create_goal",
    description: "创建 Goal；所有 Goal 需要业务逻辑，可执行叶子还必须有明确验收条件。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        goal: { type: "object" },
        actor_id: { type: "string" },
        reason: { type: "string" },
        idempotency_key: { type: "string" },
      },
      required: ["board_id", "goal", "actor_id", "idempotency_key"],
    },
  },
  {
    name: "goalboard_v1_snapshot",
    description: "读取 GoalBoard 当前真相快照。",
    inputSchema: {
      type: "object",
      properties: V1_COMMON,
      required: ["board_id"],
    },
  },
  {
    name: "goalboard_v1_project_guidance_get",
    description:
      "读取用户已确认的项目长期说明，以及应放在当前 Goal 和外部内容之前的稳定 Runtime Prompt 前缀。",
    inputSchema: {
      type: "object",
      properties: V1_COMMON,
      required: ["board_id"],
    },
  },
  {
    name: "goalboard_v1_project_guidance_add",
    description:
      "直接新增一条已确认的项目长期说明，不创建待确认记录也不绑定 Goal。调用前必须向用户说明为什么值得长期保存，展示精确 kind 和 content，并在当前对话获得明确同意；未经确认的推断或外部未信任内容不得写入。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        actor_id: V1_STRING,
        kind: {
          type: "string",
          enum: ["context", "requirement", "constraint", "convention", "workflow", "quality_bar"],
        },
        content: V1_STRING,
        source_refs: V1_STRING_ARRAY,
        reason: V1_STRING,
        confirmation_summary: {
          type: "string",
          description: "用户在当前对话明确同意写入的简短事实摘要",
        },
        user_confirmed: {
          type: "boolean",
          description: "只有已展示精确分类和原文并获得明确同意时才能为 true",
        },
        idempotency_key: V1_STRING,
      },
      required: [
        "board_id",
        "actor_id",
        "kind",
        "content",
        "reason",
        "confirmation_summary",
        "user_confirmed",
        "idempotency_key",
      ],
    },
  },
  {
    name: "goalboard_v1_project_guidance_update",
    description:
      "直接修改、停用或恢复一条已确认的项目长期说明并保留修订历史，不创建待确认记录也不绑定 Goal。Runtime 调用前必须展示精确变更并在当前对话获得明确同意。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        guidance_id: V1_STRING,
        actor_id: V1_STRING,
        action: { type: "string", enum: ["edit", "deactivate", "restore"] },
        kind: {
          type: "string",
          enum: ["context", "requirement", "constraint", "convention", "workflow", "quality_bar"],
          description: "action=edit 时必填",
        },
        content: { type: "string", description: "action=edit 时必填" },
        source_refs: V1_STRING_ARRAY,
        reason: V1_STRING,
        confirmation_summary: {
          type: "string",
          description: "用户在当前对话明确同意这次变更的简短事实摘要",
        },
        user_confirmed: {
          type: "boolean",
          description: "只有已展示精确变更并获得明确同意时才能为 true",
        },
        idempotency_key: V1_STRING,
      },
      required: [
        "board_id",
        "guidance_id",
        "actor_id",
        "action",
        "reason",
        "confirmation_summary",
        "user_confirmed",
        "idempotency_key",
      ],
    },
  },
  {
    name: "goalboard_v1_contract",
    description:
      "读取一个 Goal 的完整 Contract、关系、风险、执行事实和可供用户打开的稳定页面地址。parent_contract_coverage 会逐项说明它对父 Goal 承诺结果与完成条件的贡献；record_status=unrecorded 表示历史数据未记录映射，不代表父级能力已被覆盖。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        goal_id: { type: "string" },
        web_base_url: {
          type: "string",
          description: "GoalBoard Web 根地址；默认读取 GOALBOARD_WEB_URL 或 http://127.0.0.1:4173",
        },
      },
      required: ["board_id", "goal_id"],
    },
  },
  {
    name: "goalboard_v1_ready",
    description: "返回 Runtime 可自主选择并领取的 Ready Goals。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        actor_id: { type: "string" },
        role: V1_CLAIM_ROLE,
        capabilities: { type: "array", items: { type: "string" } },
        goal_mode_attestation: { type: "boolean" },
      },
      required: ["board_id", "actor_id"],
    },
  },
  {
    name: "goalboard_v1_available",
    description:
      "返回统一动作投影。action_projections 是当前权威入口：每个 Goal 可有多个动作，但只有一个稳定 primary_action。Runtime 先暂选候选，再读 goalboard_v1_contract 核对当前请求是否仍在 scope 内，最后用 goalboard_v1_select_goal 提交 action_id + action_token。执行、Evidence、Review 与 Risk 门禁满足后会自动释放和完成，不再手动 complete。旧 Available 字段仅作边界兼容。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        actor_id: { type: "string" },
        capabilities: { type: "array", items: { type: "string" } },
        goal_mode_attestation: { type: "boolean" },
        detail_level: {
          type: "string",
          enum: ["summary", "full"],
          description: "默认 summary；full 保留旧版完整 Goal、Policy、Impact 与 Contract 详情。",
        },
      },
      required: ["board_id", "actor_id"],
    },
  },
  {
    name: "goalboard_v1_planning_methods",
    description: "读取当前项目的方法目录、所选完整方法正文和项目必选组合。推荐先传 include_instructions=false 获取轻量目录与 composition.method_pack_ids，再传 method_ids 精确读取每个已选 methods[].instructions；catalog_id 与 returned_method_ids 用于核对两次读取属于同一目录且正文没有遗漏。不传可选参数时保留旧版完整响应。Runtime 在创建、拆分或重连 Goal 前，必须完整阅读每个已选方法的 instructions，并把多套方法作为互补的规划 Skill 一起使用。项目组合是必须使用的下限，不是方法选择的上限。Runtime 还要检查各主题的提供者产出与消费者用途，召回遗漏的相关方法，并在真实产出消费存在时建立硬依赖；不得按类型、列表顺序、固定数量或一般相关性预设选择和依赖。项目覆盖个人，个人覆盖内置冷启方法。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        method_ids: {
          type: "array",
          minItems: 1,
          uniqueItems: true,
          items: { type: "string", minLength: 1 },
          description: "可选；只返回这些规划方法，并保持请求顺序。未知 ID 会明确报错。",
        },
        include_instructions: {
          type: "boolean",
          description: "默认 true；false 返回用于选择的轻量目录，不展开 instructions、steps 和规则正文。",
        },
      },
      required: ["board_id"],
    },
  },
  {
    name: "goalboard_v1_planning_method_save",
    description: "在用户明确确认后保存一条项目级规划方法或覆盖；它会影响此项目后续拆分与依赖判断。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        method: PLANNING_METHOD_PACK,
        actor_id: V1_STRING,
        user_confirmed: { type: "boolean" },
      },
      required: ["board_id", "method", "actor_id", "user_confirmed"],
    },
  },
  {
    name: "goalboard_v1_planning_analyze_change",
    description: "用户提出新要求时，只读计算受影响的上层 Goal、下游消费者、变更 Goal 直接消费的相邻上游依赖、可复用工作和重新审查顺序；不会自动改树。Goal Tree 决定成功后也会在 semantic_review 中自动返回同一影响结构。",
    inputSchema: {
      type: "object",
      properties: { ...V1_COMMON, changed_goal_ids: V1_STRING_ARRAY },
      required: ["board_id", "changed_goal_ids"],
    },
  },
  {
    name: "goalboard_v1_planning_graph_check",
    description: "只读检查整张 Goal 图的缺失引用、重复关系、父子循环、依赖循环和组合执行循环。",
    inputSchema: {
      type: "object",
      properties: V1_COMMON,
      required: ["board_id"],
    },
  },
  {
    name: "goalboard_v1_explain",
    description: "解释一个 Goal 的当前动作为什么可领取或被什么阻塞；role=executor 的 ready 只表示执行 Claim 就绪，不表示 complete 的验收或 completion Risk 门禁已经通过。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        goal_id: { type: "string" },
        actor_id: { type: "string" },
        role: V1_CLAIM_ROLE,
        capabilities: { type: "array", items: { type: "string" } },
        goal_mode_attestation: { type: "boolean" },
      },
      required: ["board_id", "goal_id", "actor_id"],
    },
  },
  {
    name: "goalboard_v1_claim",
    description: "Runtime 原子领取自己选择的 Ready Goal；GoalBoard 不分发任务。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        goal_id: { type: "string" },
        actor_id: { type: "string" },
        role: V1_CLAIM_ROLE,
        capabilities: { type: "array", items: { type: "string" } },
        goal_mode_attestation: { type: "boolean" },
        lease_seconds: V1_LEASE_SECONDS,
        strengthen_policy: { type: "object" },
        action_id: V1_STRING,
        action_token: V1_STRING,
        idempotency_key: { type: "string" },
      },
      required: ["board_id", "goal_id", "actor_id", "idempotency_key"],
    },
  },
  {
    name: "goalboard_v1_select_goal",
    description:
      "调用前先读 goalboard_v1_contract，确认当前请求仍在 accepted Contract 的范围内；再按 Available 返回的 action_id + action_token 原子创建 Claim 和 Run，并立即返回新动作投影。旧 goal/role 调用只在唯一动作匹配时兼容。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        goal_id: { type: "string" },
        actor_id: { type: "string" },
        role: V1_CLAIM_ROLE,
        capabilities: { type: "array", items: { type: "string" } },
        goal_mode_attestation: { type: "boolean" },
        lease_seconds: V1_LEASE_SECONDS,
        strengthen_policy: { type: "object" },
        action_id: V1_STRING,
        action_token: V1_STRING,
        idempotency_key: { type: "string" },
      },
      required: ["board_id", "goal_id", "actor_id", "idempotency_key"],
    },
  },
  {
    name: "goalboard_v1_draft_dialogue_start",
    description:
      "初始化待澄清 Goal 的自然语言对话：无 goal_id 时原子创建最小 Draft、Claim 和 Run；已有 Goal 时保持原 Goal，并复用当前 Runtime 已选择的 clarifier Run。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        rough_idea: V1_STRING,
        draft_title: V1_STRING,
        goal_id: V1_STRING,
        actor_id: V1_STRING,
        capabilities: V1_STRING_ARRAY,
        goal_mode_attestation: { type: "boolean" },
        lease_seconds: V1_LEASE_SECONDS,
        idempotency_key: V1_STRING,
      },
      required: ["board_id", "rough_idea", "actor_id", "idempotency_key"],
    },
  },
  {
    name: "goalboard_v1_draft_dialogue_turn",
    description:
      "持久化用户本轮自然语言回答、当前理解、可追溯事实、明确假设及唯一下一步；没有关键未知项时写入待确认提案摘要。默认只返回本轮最新 turn、dialogue checkpoint 和 lifecycle 状态；仅在明确读取历史时用 include_history 分页返回 turns。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        goal_id: V1_STRING,
        run_id: V1_STRING,
        actor_id: V1_STRING,
        user_message: V1_STRING,
        current_understanding: V1_STRING,
        known_facts: { type: "array", items: DRAFT_DIALOGUE_FACT },
        assumptions: { type: "array", items: DRAFT_DIALOGUE_ASSUMPTION },
        next_question: { type: ["string", "null"] },
        proposal_summary: { type: ["string", "null"] },
        include_history: {
          type: "boolean",
          default: false,
          description: "默认 false；true 时按 history_limit / history_before_turn_index 返回一页历史 turns",
        },
        history_limit: {
          type: "integer",
          minimum: 1,
          maximum: 100,
          default: 20,
          description: "仅 include_history=true 时使用；返回不超过该数量的最近历史 turn",
        },
        history_before_turn_index: {
          type: "integer",
          minimum: 1,
          description: "仅 include_history=true 时使用；只返回 turn_index 小于该游标的更早记录",
        },
        idempotency_key: V1_STRING,
      },
      required: [
        "board_id",
        "goal_id",
        "run_id",
        "actor_id",
        "user_message",
        "current_understanding",
        "idempotency_key",
      ],
    },
  },
  {
    name: "goalboard_v1_draft_dialogue_resume",
    description:
      "在新 Session 中读取已持久化的 Goal 澄清 checkpoint；若没有活跃 Run，当前 Runtime 原子恢复 clarifier Claim 和 Run。默认不重复返回完整 turns；需要回看时用 include_history、history_limit 和 history_before_turn_index 分页读取。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        goal_id: V1_STRING,
        actor_id: V1_STRING,
        capabilities: V1_STRING_ARRAY,
        goal_mode_attestation: { type: "boolean" },
        lease_seconds: V1_LEASE_SECONDS,
        include_history: {
          type: "boolean",
          default: false,
          description: "默认 false；true 时按 history_limit / history_before_turn_index 返回一页历史 turns",
        },
        history_limit: {
          type: "integer",
          minimum: 1,
          maximum: 100,
          default: 20,
          description: "仅 include_history=true 时使用；返回不超过该数量的最近历史 turn",
        },
        history_before_turn_index: {
          type: "integer",
          minimum: 1,
          description: "仅 include_history=true 时使用；只返回 turn_index 小于该游标的更早记录",
        },
        idempotency_key: V1_STRING,
      },
      required: ["board_id", "goal_id", "actor_id", "idempotency_key"],
    },
  },
  {
    name: "goalboard_v1_goal_tree_propose",
    description:
      "当前 clarifier Runtime 原子提交一份包含多个 Goal Tree 变更条目的待确认提案；已接受叶子 Goal 的 active executor 或 revalidator Run 也可以为自己的同一 Goal 提交仅含 Risk 生命周期变更的提案，不能借此修改 Contract、关系或其他 Goal。提交不会提前改写 canonical GoalBoard，可通过 supersedes_proposal_id 创建修订版本；该字段接受 native Proposal ID，也接受 goal_tree_read 返回的 legacy Contract Proposal raw/synthetic handle，并会让旧 Contract Proposal 原子退出待决定状态。Legacy Candidate 请使用 candidate item 晋升，Legacy Rewire 则在等价关系变更确认落地后自动关闭，不能把这两类 handle 当成普通修订。包含 5 项及以上变化时，必须提供 narrative，并为每项提供 explanation，让审批人直接看到原问题、变更后主链路、逐项效果、非目标和 change 依赖。改变已有 Risk 生命周期本身是一条正式 Goal：若 clarifier 的 Goal 仍是 Draft，必须在同一提案中用完整 Contract 把它接受为 closed_leaf，不能只改 Risk 后留下空 Draft。closed_compound 的 decomposition_review 必须用 contract_coverage 逐项映射父 promised_outputs / acceptance_criteria 到后代 Contract，部分覆盖或仍需集成时保持父 Goal 开放。Risk 的 treatment=mitigate 表示降低策略；措施完成后更新为 state=resolved 并提供 resolution_basis，不存在 state=mitigated。晋升已有 pending Candidate 时使用 kind=candidate、operation=update，payload 同时提供 candidate_id、最终 proposed_goal 与 proposed_relations，并把 Candidate 和目标 Goal 都列入 affected_objects；严格启动对账还需 formal_goal_id 与 materialized_by_proposal_id。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        actor_id: V1_STRING,
        discovered_in_run_id: V1_STRING,
        root_goal_id: { type: ["string", "null"] },
        summary: V1_STRING,
        narrative: GOAL_TREE_PROPOSAL_NARRATIVE,
        items: { type: "array", items: GOAL_TREE_ITEM },
        base_event_cursor: { type: "integer", minimum: 0 },
        supersedes_proposal_id: {
          type: ["string", "null"],
          description: "要修订的 native Proposal ID，或 pending legacy Contract Proposal 的 raw/synthetic handle；其他 legacy 类型会返回精确恢复动作",
        },
        idempotency_key: V1_STRING,
      },
      required: ["board_id", "actor_id", "discovered_in_run_id", "summary", "items", "idempotency_key"],
    },
  },
  {
    name: "goalboard_v1_goal_tree_read",
    description:
      "读取原生 Goal Tree 提案与无损映射的历史 Contract Proposal、Candidate、Rewire；可按 proposal_id 或 root Goal 恢复对话。历史记录的原始 raw ID 与 legacy-* 映射 synthetic ID 都能读取，响应统一返回可决定的映射 proposal_id 与 item_id，可原样交给 goal_tree_check 或 goal_tree_decide。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        proposal_id: V1_STRING,
        root_goal_id: V1_STRING,
        include_legacy: { type: "boolean" },
      },
      required: ["board_id"],
    },
  },
  {
    name: "goalboard_v1_goal_tree_check",
    description:
      "按每个条目真正依赖的 canonical 事实检查并发变化，并在可回滚预检中运行与决定阶段相同的物化不变量；原生 Goal Tree Proposal 和 legacy Contract Proposal 均可使用，后者可传原始 raw ID 或读取结果中的映射 ID。某个条目冲突不会改写 canonical Goal Tree，也不会隐藏其他条目的检查结果。已接受 Goal 的需求变化使用同一 Goal ID 的 native contract-update revision；Relation、Impact 和 Risk 变化必须另列显式条目。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        proposal_id: V1_STRING,
        actor_id: V1_STRING,
        idempotency_key: V1_STRING,
      },
      required: ["board_id", "proposal_id", "actor_id", "idempotency_key"],
    },
  },
  {
    name: "goalboard_v1_goal_tree_decide",
    description:
      "把用户对 Goal Tree 提案的决定物化；goal_tree_read 返回的 native 或 legacy handle 都可直接使用，历史 Contract Proposal、Candidate、Rewire 的单项 confirm/reject 会分派到原有审计路径。逐项决定仍允许互不依赖的安全条目分别落地，confirm_all_pending 则全有或全无，任一冲突都会让整份确认保持未写入。成功应用后响应和 proposal readback 的 semantic_review 会把结构校验通过与仍需复核的祖先、下游消费者、相邻上游依赖分开，并返回 review_affected_subgraph；Runtime 必须先复核这些 Contract，任何后续重编排仍须新 Proposal 和用户确认。Draft 上的 Risk 生命周期条目不能脱离同一轮确认中的完整 Goal Contract 单独落地；两者任一冲突时 canonical Goal 与 Risk 都不改变。管理入口必须提供可审计的用户与消息引用。",
    inputSchema: {
      type: "object",
      properties: {
        ...V1_COMMON,
        proposal_id: V1_STRING,
        runtime_actor_id: V1_STRING,
        authority: {
          type: "object",
          properties: {
            actor_id: V1_STRING,
            actor_kind: { type: "string", enum: ["user"] },
            authority_source: { type: "string", enum: ["runtime_dialogue", "web", "management"] },
            conversation_ref: V1_STRING,
            message_ref: V1_STRING,
            whole_confirmation_prompted: { type: "boolean" },
            prompted_proposal_id: V1_STRING,
          },
          required: ["actor_id", "actor_kind", "authority_source", "conversation_ref", "message_ref"],
        },
        decisions: { type: "array", minItems: 1, items: GOAL_TREE_ITEM_DECISION },
        reason: V1_STRING,
        confirm_all_pending: { type: "boolean" },
        idempotency_key: V1_STRING,
      },
      required: ["board_id", "proposal_id", "authority", "idempotency_key"],
    },
  },
  v1PayloadTool(
    "goalboard_v1_claim_renew",
    "由当前领取者为仍未过期的 active Claim 续租；actor_id 必须原样复用领取时的值。保持同一个 Claim 和 Run，不会复活过期工作。若 compaction 后误用其他 actor_id，claim.not_owner 会返回 owner_actor_id 和只限同一 Runtime 连续工作的安全重试动作。",
    {
      claim_id: V1_STRING,
      actor_id: V1_STRING,
      lease_seconds: V1_RENEW_LEASE_SECONDS,
      idempotency_key: V1_STRING,
    },
    ["claim_id", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_release",
    "由领取者释放 Claim。成功响应会返回 handoff：先只读调用 goalboard_v1_available 刷新权威下一项，再在当前用户授权范围内继续，或明确报告需要的人类决定、权限或输入；读取 Available 本身不需要再次确认，handoff 不授权无关工作。",
    { claim_id: V1_STRING, actor_id: V1_STRING, reason: V1_STRING, idempotency_key: V1_STRING },
    ["claim_id", "actor_id", "reason", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_revoke_claim",
    "管理入口或恢复流程撤销失效 Claim，并在同一事务中中断其未结束 Run；不向 Runtime MCP 暴露。",
    { claim_id: V1_STRING, actor_id: V1_STRING, reason: V1_STRING, idempotency_key: V1_STRING },
    ["claim_id", "actor_id", "reason", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_relation_add",
    "登记 Goal 关系；Runtime 发现的新关系应优先随 Candidate 提议。",
    {
      relation: {
        type: "object",
        properties: {
          from_goal_id: V1_STRING,
          to_goal_id: V1_STRING,
          type: {
            type: "string",
            enum: ["part_of", "depends_on", "conflicts_with", "mitigates", "extends", "replaces", "corrects", "invalidates", "migrates_from"],
          },
          state: { type: "string", enum: ["proposed", "active"] },
          reason: V1_STRING,
        },
        required: ["from_goal_id", "to_goal_id", "type", "reason"],
      },
      actor_id: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["relation", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_impact_add",
    "登记 Goal 的 Impact Surface。",
    {
      impact: {
        type: "object",
        properties: {
          goal_id: V1_STRING,
          surface: V1_STRING,
          access: { type: "string", enum: ["read", "write", "decide", "exclusive"] },
          input_snapshot: { type: ["string", "null"] },
          state: { type: "string", enum: ["proposed", "confirmed"] },
          reason: V1_STRING,
        },
        required: ["goal_id", "surface", "access", "reason"],
      },
      actor_id: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["impact", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_policy_set",
    "设置 Goal Mode 与 Review Policy。",
    {
      binding: {
        type: "object",
        properties: { goal_id: { type: ["string", "null"] }, policy: { type: "object" }, reason: V1_STRING },
        required: ["policy", "reason"],
      },
      actor_id: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["binding", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_risk_add",
    "登记并关联 Risk。",
    {
      risk: {
        type: "object",
        properties: {
          risk_id: V1_STRING,
          goal_ids: V1_STRING_ARRAY,
          description: V1_STRING,
          probability: V1_STRING,
          impact: V1_STRING,
          affected_surfaces: V1_STRING_ARRAY,
          trigger: V1_STRING,
          treatment: { type: "string", enum: ["accept", "mitigate", "avoid", "defer"] },
          blocking_mode: { type: "string", enum: ["none", "claim", "completion", "invalidate_on_trigger"] },
          revisit_condition: V1_STRING,
          owner: V1_STRING,
        },
        required: ["goal_ids", "description", "probability", "impact", "trigger", "treatment", "blocking_mode", "revisit_condition", "owner"],
      },
      actor_id: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["risk", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_risk_state",
    "更新 Risk 状态并执行失效影响。state=resolved 时必须提供 resolution_basis：解决摘要、至少一条证据引用，以及明确的 residual_gaps（没有时传空数组）。",
    {
      risk: {
        type: "object",
        properties: {
          risk_id: V1_STRING,
          state: { type: "string", enum: ["open", "triggered", "resolved", "accepted", "expired"] },
          reason: V1_STRING,
          resolution_basis: {
            type: "object",
            properties: {
              summary: V1_STRING,
              evidence_refs: { ...V1_STRING_ARRAY, minItems: 1 },
              residual_gaps: V1_STRING_ARRAY,
            },
            required: ["summary", "evidence_refs", "residual_gaps"],
          },
          goal_id: V1_STRING,
          contract_revision: { type: "integer", minimum: 1 },
          action_id: V1_STRING,
          action_token: V1_STRING,
        },
        required: ["risk_id", "state", "reason"],
      },
      actor_id: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["risk", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_active_goal",
    "设置当前产品 Goal。",
    { goal_id: V1_STRING, reason: V1_STRING, actor_id: V1_STRING, idempotency_key: V1_STRING },
    ["goal_id", "reason", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_goal_trash",
    "仅在当前用户已明确确认后，把当前项目的一条 Goal 移入可恢复回收站；不会物理删除历史。",
    {
      goal_id: V1_STRING,
      actor_id: V1_STRING,
      user_confirmed: {
        type: "boolean",
        description: "当前对话中的用户已明确要求移入回收站；含糊的“清理一下”不能传 true",
      },
      reason: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["goal_id", "actor_id", "user_confirmed", "reason", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_goal_trash_list",
    "读取当前项目回收站中的 Goal；只读，不要求用户确认，也不打开 Web。",
    {},
    [],
  ),
  v1PayloadTool(
    "goalboard_v1_goal_restore",
    "仅在当前用户已明确确认后，恢复当前项目回收站中的一条 Goal 及可安全恢复的 Relation。",
    {
      goal_id: V1_STRING,
      actor_id: V1_STRING,
      user_confirmed: {
        type: "boolean",
        description: "当前对话中的用户已明确要求恢复这条 Goal",
      },
      reason: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["goal_id", "actor_id", "user_confirmed", "reason", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_run_start",
    "为有效 Claim 开始 Run。",
    { claim_id: V1_STRING, actor_id: V1_STRING, idempotency_key: V1_STRING },
    ["claim_id", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_revalidate",
    "由正在执行的 revalidator Run 提交核对证据；只有依赖、风险和 Contract 门禁都通过时才恢复 valid。",
    {
      goal_id: V1_STRING,
      run_id: V1_STRING,
      actor_id: V1_STRING,
      reason: V1_STRING,
      evidence_refs: V1_STRING_ARRAY,
      contract_revision: { type: "integer", minimum: 1 },
      action_token: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["goal_id", "run_id", "actor_id", "reason", "evidence_refs", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_rework_request",
    "当已完成的执行和复核在完成门禁前被新的可追溯反证推翻时，请求同一 unmet Goal 返回执行。它只让受影响验收条件要求 fresh Evidence 并重开 Review；不修改 Contract、不删除历史，也不解决 completion Risk。",
    {
      goal_id: V1_STRING,
      actor_id: V1_STRING,
      criterion_ids: { ...V1_STRING_ARRAY, minItems: 1 },
      reason: V1_STRING,
      evidence_refs: { ...V1_STRING_ARRAY, minItems: 1 },
      idempotency_key: V1_STRING,
    },
    ["goal_id", "actor_id", "criterion_ids", "reason", "evidence_refs", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_run_report",
    "报告 Run 阻塞或终态并立即返回新动作投影。completed 后若 Evidence 已齐会自动释放；若尚缺依据，Claim 保留且主动作变为补齐完成依据。",
    {
      run_id: V1_STRING,
      actor_id: V1_STRING,
      state: { type: "string", enum: ["started", "blocked", "completed", "failed", "abandoned"] },
      block_reason: { type: ["string", "null"] },
      output_refs: V1_STRING_ARRAY,
      discovery_refs: V1_STRING_ARRAY,
      contract_revision: { type: "integer", minimum: 1 },
      action_token: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["run_id", "actor_id", "state", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_evidence_submit",
    "提交与验收条件绑定的 Evidence；GoalBoard 会只读预检当前项目内文件、当前 canonical Git 仓库正式登记的隔离 worktree 文件与 Markdown anchor。超过 512 KiB 的项目内普通文件会在确认路径安全后登记为 UNVERIFIED，不会全文读取或打开；调用方提供的 digest 只按原样记录，不代表 GoalBoard 已核验，建议同时提交小型 sidecar summary。外部、不透明或 file:/// 机器本地 locator 也会保留但明确标为 UNVERIFIED；file:/// 只登记、不可从 Web 打开。`human_verdict` 只用于把用户针对唯一待决人工验收的明确原话交接到预填表单：必须使用 Contract 返回的 criterion_ids、conversation:// 来源和原话 digest；它不是 canonical Human Review，也不允许 Runtime 代替用户提交。",
    {
      goal_id: V1_STRING,
      actor_id: V1_STRING,
      criterion_ids: V1_STRING_ARRAY,
      run_id: { type: ["string", "null"] },
      review_id: { type: ["string", "null"] },
      kind: { type: "string", enum: ["test", "measurement", "artifact", "inspection", "attestation", "human_verdict"] },
      locator: {
        type: "string",
        description:
          "可验证的项目文件格式：普通相对路径 docs/review.md#checks、输入别名 repo:docs/review.md#checks、canonical 格式 project://docs/review.md#checks，或当前 canonical workspace 内的绝对路径。若绝对路径位于当前 canonical Git 仓库通过 git worktree 正式登记的隔离工作树，GoalBoard 会在 realpath containment 通过后同样验证，并记录实际 worktree 根；不同仓库、伪造 .git 目录和 symlink 逃逸仍拒绝。安全的 repo: 输入会统一存为 project://；超过 512 KiB 的项目内文件只确认路径并以 UNVERIFIED 登记，不可在 Web 预览。跨仓或项目外的 file:///path/to/artifact 可仅登记为 UNVERIFIED：GoalBoard 不会读取或确认文件存在，调用方提供的 digest 也未核验；HTTP 与其他不透明协议同样保留为 UNVERIFIED。",
      },
      digest: { type: ["string", "null"] },
      result: { type: "string", enum: ["passed", "failed", "inconclusive"] },
      contract_revision: { type: "integer", minimum: 1 },
      action_token: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["goal_id", "actor_id", "criterion_ids", "kind", "locator", "result", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_evidence_correct",
    "以不可变更正记录替代或撤销当前 Runtime 自己提交的 Evidence；原记录始终保留，完成与 Review 只认当前有效 Evidence。",
    {
      goal_id: V1_STRING,
      actor_id: V1_STRING,
      target_evidence_id: V1_STRING,
      action: { type: "string", enum: ["supersede", "retract"] },
      replacement_evidence_id: { type: ["string", "null"] },
      reason: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["goal_id", "actor_id", "target_evidence_id", "action", "reason", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_review_submit",
    "提交 Review；human approval 还必须声明 actor_kind=user。",
    {
      goal_id: V1_STRING,
      obligation_id: V1_STRING,
      actor_id: V1_STRING,
      actor_kind: { type: "string", enum: ["user", "runtime"] },
      verdict: { type: "string", enum: ["pass", "fail", "needs_changes", "inconclusive"] },
      evidence_refs: V1_STRING_ARRAY,
      reasoning: V1_STRING,
      contract_revision: { type: "integer", minimum: 1 },
      action_token: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["goal_id", "obligation_id", "actor_id", "verdict", "reasoning", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_complete",
    "兼容与异常修复入口：重新检查并修复 Goal 完成状态。正常链路会自动完成，不应常规调用。",
    { goal_id: V1_STRING, actor_id: V1_STRING, idempotency_key: V1_STRING },
    ["goal_id", "actor_id", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_dependency_propose",
    "提交带依据、证据、方向和拒绝影响的 Dependency Proposal；只创建待用户决定的 Rewire。",
    {
      actor_id: V1_STRING,
      discovered_in_run_id: V1_STRING,
      dependencies: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          properties: {
            from_goal_id: V1_STRING,
            to_goal_id: V1_STRING,
            type: { type: "string", enum: ["depends_on"] },
            action: { type: "string", enum: ["add", "deactivate"] },
            reason: V1_STRING,
            basis: {
              type: "string",
              enum: [
                "contract_output",
                "code_reference",
                "test_dependency",
                "business_sequence",
                "impact_conflict",
                "risk_policy",
              ],
            },
            evidence_refs: V1_STRING_ARRAY,
            impact_if_rejected: V1_STRING,
            confidence: { type: "number", minimum: 0, maximum: 1 },
            direction_reason: V1_STRING,
          },
          required: [
            "from_goal_id",
            "to_goal_id",
            "type",
            "action",
            "reason",
            "basis",
            "evidence_refs",
            "impact_if_rejected",
            "confidence",
            "direction_reason",
          ],
        },
      },
      blocking_mode: { type: "string", enum: ["none", "current_run"] },
      idempotency_key: V1_STRING,
    },
    ["actor_id", "discovered_in_run_id", "dependencies", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_contract_propose",
    "clarifier 为同一个 Draft 提交完整 Contract 补全提案；canonical Goal 在用户确认前保持不变。proposed_goal.goal_id 必须是原 Draft ID；acceptance_criteria 必须是含 criterion_id、statement、decision_method、pass_condition、required_evidence 的对象数组；accepted / closed_leaf 还必须提供 proposed_goal.leaf_readiness，并让 acceptance_criterion_ids 一一对应。",
    {
      goal_id: V1_STRING,
      actor_id: V1_STRING,
      discovered_in_run_id: V1_STRING,
      proposed_goal: CONTRACT_PROPOSAL_GOAL_PAYLOAD,
      field_sources: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          properties: {
            field: {
              type: "string",
              enum: [
                "title", "outcome", "why", "business_logic", "in_scope", "out_of_scope",
                "constraints", "required_inputs", "promised_outputs", "priority",
                "acceptance_criteria", "review_policy",
              ],
            },
            source_kind: {
              type: "string",
              enum: ["user_answer", "repository_fact", "document_fact", "runtime_inference"],
            },
            source_refs: V1_STRING_ARRAY,
            confidence: { type: "number", minimum: 0, maximum: 1 },
            rationale: V1_STRING,
            status: { type: "string", enum: ["proposed"] },
            requires_user_confirmation: { type: "boolean", enum: [true] },
          },
          required: [
            "field", "source_kind", "source_refs", "confidence", "rationale", "status",
            "requires_user_confirmation",
          ],
        },
      },
      review_policy: {
        type: "object",
        properties: GOAL_TREE_POLICY_FIELDS,
        required: [
          "goal_mode",
          "required_capabilities",
          "self_verification",
          "cross_reviewers",
          "adversarial_reviewers",
          "human_approval",
          "max_lease_seconds",
        ],
      },
      proposed_impacts: { type: "array", items: { type: "object" } },
      proposed_risks: { type: "array", items: { type: "object" } },
      dependency_rewire_ids: V1_STRING_ARRAY,
      idempotency_key: V1_STRING,
    },
    [
      "goal_id", "actor_id", "discovered_in_run_id", "proposed_goal", "field_sources",
      "review_policy", "idempotency_key",
    ],
  ),
  v1PayloadTool(
    "goalboard_v1_candidate_submit",
    "提交澄清或执行中发现的 Candidate Goal、关系、影响与 Risk 提案。",
    {
      actor_id: V1_STRING,
      discovered_in_run_id: { type: ["string", "null"] },
      proposed_goal: { type: "object" },
      proposed_relations: { type: "array", items: { type: "object" } },
      proposed_impacts: { type: "array", items: { type: "object" } },
      proposed_risks: { type: "array", items: { type: "object" } },
      blocking_mode: { type: "string", enum: ["none", "current_run", "dependent_claims"] },
      idempotency_key: V1_STRING,
    },
    ["actor_id", "proposed_goal", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_contract_decide",
    "可信用户入口确认或拒绝同一 Draft 的 Contract 补全提案；Runtime 不可调用。",
    {
      proposal_id: V1_STRING,
      actor_id: V1_STRING,
      actor_kind: { type: "string", enum: ["user", "runtime"] },
      decision: { type: "string", enum: ["approved", "rejected"] },
      reason: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["proposal_id", "actor_id", "actor_kind", "decision", "reason", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_candidate_decide",
    "可信用户调用面决定 Candidate Goal；不要向未受信 Runtime 暴露。",
    {
      candidate_id: V1_STRING,
      actor_id: V1_STRING,
      actor_kind: { type: "string", enum: ["user", "runtime"] },
      decision: { type: "string", enum: ["approved", "rejected", "dismissed"] },
      reason: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["candidate_id", "actor_id", "actor_kind", "decision", "reason", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_rewire_confirm",
    "可信用户调用面决定是否应用 Candidate 或 Dependency Proposal 引起的关系调整；不要向 Runtime 暴露。",
    {
      rewire_id: V1_STRING,
      actor_id: V1_STRING,
      actor_kind: { type: "string", enum: ["user", "runtime"] },
      decision: { type: "string", enum: ["confirmed", "rejected"] },
      reason: V1_STRING,
      idempotency_key: V1_STRING,
    },
    ["rewire_id", "actor_id", "actor_kind", "reason", "idempotency_key"],
  ),
  v1PayloadTool(
    "goalboard_v1_import_v3",
    "导入 V3 可安全映射字段，并返回必须重新生成的语义。",
    { legacy: { type: "object" }, actor_id: V1_STRING, idempotency_key: V1_STRING },
    ["legacy", "actor_id", "idempotency_key"],
  ),
];
